#!/bin/sh

SEARCH_PATH=$(grep -rl amdgpu /sys/class/drm/card*/device/hwmon/hwmon*/name)
DEVICE_PATH=$(echo $SEARCH_PATH | sed 's/\/hwmon.*//g')
HWMON_PATH=$(echo $SEARCH_PATH | sed 's/\/name//g')

echo "$SEARCH_PATH $DEVICE_PATH $HWMON_PATH"

echo 'manual'    > $DEVICE_PATH/power_dpm_force_performance_level
echo '1'         > $DEVICE_PATH/pp_power_profile_mode
echo '260000000' > $HWMON_PATH/power1_cap
echo 's 1 2700'  > $DEVICE_PATH/pp_od_clk_voltage
echo 'vo -70'    > $DEVICE_PATH/pp_od_clk_voltage
echo 'c'         > $DEVICE_PATH/pp_od_clk_voltage

